language: c

dist: xenial

os: linux

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - python3
      - libxrandr-dev
      - libpango1.0-dev
      - libmenu-cache-dev

script: make && make test

after_success:
  - export CODECOV_TOKEN="786edde0-bf90-4e6b-9299-cc3f18033616"
  - bash <(curl -s https://codecov.io/bash)
