language: c

dist: xenial

os: linux

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - make
      - pkg-config
      - python3.5
      - libx11-dev
      - libxrandr-dev
      - libcairo2-dev
      - libpango1.0-dev
      - librsvg2-dev
      - libxml2-dev
      - libglib2.0-dev
      - libmenu-cache-dev

script: make && make test

