language: c

dist: xenial

os: linux

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - python3
      - libxrandr-dev
      - libpango1.0-dev
      - libmenu-cache-dev

script: make && make test
